Repository ARMmbed/meta-mbl, pull requests merged in 2019-08, with the labels that each got.

#643 meta-mbl-distro: dropbear: Fix systemd drop-in path installation
  meta-mbl-distro/recipes-core/dropbear/dropbear_%.bbappend
Labels: affects: mbl-os-0.8

#641 Update partition table
  meta-mbl-distro/classes/mbl-partitions.bbclass
  meta-mbl-distro/conf/distro/mbl-directories.conf
  meta-mbl-distro/recipes-core/base-files/base-files_%.bbappend
  meta-mbl-distro/recipes-core/mbl-initramfs-init/files/initramfs-init-script.sh
  meta-mbl-distro/recipes-core/mbl-initramfs-init/mbl-initramfs-init_1.0.bb
  meta-mbl-distro/wic/mbl.wks.in
  meta-raspberrypi-mbl/conf/machine/raspberrypi3-mbl.conf
Labels: DO NOT MERGE

#672 meta-mbl-distro: Add root password setting for production images
  meta-mbl-distro/classes/mbl-distro-image-production.bbclass
  meta-mbl-distro/classes/mbl-extrausers.bbclass
  meta-mbl-distro/conf/distro/include/mbl-distro-production.inc
  meta-mbl-distro/recipes-extended/shadow/files/faillog.logrotate
  meta-mbl-distro/recipes-extended/shadow/shadow-sysroot_%.bbappend
  meta-mbl-distro/recipes-extended/shadow/shadow_%.bbappend
Labels: SYNCHRONIZE MERGES
