Repository ARMmbed/meta-mbl, pull requests merged in 2019-10, with the labels that each got.

#724 meta-mbl-distro: Install supplied Authorized Keys and disable passwd login
  meta-mbl-distro/classes/mbl-distro-image-common.bbclass
  meta-mbl-distro/classes/mbl-distro-image-production.bbclass
  meta-mbl-distro/classes/mbl-external-ssh-pub-key.bbclass
  meta-mbl-distro/conf/distro/include/mbl-distro-production.inc
  meta-mbl-distro/recipes-core/dropbear/dropbear/dropbear-dis-passwd-login.default
  meta-mbl-distro/recipes-core/dropbear/dropbear_%.bbappend
Labels: DO NOT MERGE, SYNCHRONIZE MERGES

#743 kernel: Configure WATCHDOG_NOWAYOUT
  meta-freescale-3rdparty-mbl/recipes-kernel/linux/files/watchdog-mbl.cfg
  meta-freescale-3rdparty-mbl/recipes-kernel/linux/linux-fslc_%.bbappend
  meta-freescale-mbl/recipes-kernel/linux/files/watchdog-mbl.cfg
  meta-freescale-mbl/recipes-kernel/linux/linux-imx_%.bbappend
  meta-mbl-bsp-common/classes/mbl-kernel-config.bbclass
  meta-raspberrypi-mbl/recipes-kernel/linux/files/raspberrypi3-mbl/watchdog-mbl.cfg
  meta-raspberrypi-mbl/recipes-kernel/linux/linux-raspberrypi_%.bbappend
Labels: DO NOT MERGE

#750 Update MBL Core revision for crypto tests
  meta-mbl-distro/conf/distro/mbl-linked-repositories.conf
Labels: SYNCHRONIZE MERGES

#749 meta-mbl-apps:recipes-core: Add recipe for mbl-watchdog-init utility.
  meta-mbl-apps/recipes-core/mbl-watchdog-init/mbl-watchdog-init.bb
  meta-mbl-distro/conf/distro/mbl-linked-repositories.conf
  meta-mbl-distro/recipes-core/images/mbl-image-initramfs.bb
  meta-mbl-distro/recipes-core/mbl-initramfs-init/files/initramfs-init-script.sh
Labels: SYNCHRONIZE MERGES

#730 create-update-payload: Update for new payload format
  meta-mbl-distro/conf/distro/mbl-linked-repositories.conf
  meta-mbl-distro/scripts/create-update-payload
Labels: SYNCHRONIZE MERGES

#756 meta-mbl-apps:mbl-cloud-client: Pass storage paths defined at DISTRO …
  meta-mbl-apps/recipes-connectivity/mbl-cloud-client/mbl-cloud-client.bb
  meta-mbl-distro/conf/distro/mbl-directories.conf
Labels: SYNCHRONIZE MERGES

#757 meta-mbl-distro:recipes-support: Add swupdate package
  meta-mbl-distro/recipes-core/packagegroups/packagegroup-mbl-production.bb
  meta-mbl-distro/recipes-support/swupdate/files/defconfig
  meta-mbl-distro/recipes-support/swupdate/swupdate_%.bbappend
Labels: SYNCHRONIZE MERGES
